[options]
addons_path = /mnt/extra-addons/addons-l10n_cu,/mnt/extra-addons/custom_muk,/mnt/extra-addons/scem,/mnt/extra-addons/shop-cubaelectronica
admin_passwd = scem
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_pass

